---
  version: 1
  schedule: 
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow: 
    collect: 
      metrics: 
        /intel/mock/foo: {}
        /intel/mock/bar: {}
        /intel/mock/*/baz: {}
      config: 
        /intel/mock: 
          name: "root"
          password: "secret"
      process: 
        - 
          plugin_name: "passthru"
          process: null
          publish: 
            - 
              plugin_name: "file"
              config: 
                file: "/tmp/snap_published_mock_file.log"
