sudo: false
language: go
go:
- 1.3.1
- 1.4
before_install:
- cp .netrc ~
- chmod 600 .netrc
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get -u github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/vet
- go get golang.org/x/tools/cmd/goimports
- go get github.com/smartystreets/goconvey/convey
- if [ ! -d $PULSE_SOURCE ]; then mkdir -p $HOME/gopath/src/github.com/intelsdilabs; ln -s $TRAVIS_BUILD_DIR $PULSE_SOURCE; fi # CI for forks not from intelsdilabs
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
env:
  global:
    - PULSE_SOURCE=/home/travis/gopath/src/github.com/intelsdilabs/pulse
    - PULSE_PATH=/home/travis/gopath/src/github.com/intelsdilabs/pulse/build    
install:
- gem install facter
- cd $PULSE_SOURCE # change dir into source
- go get -d github.com/docker/libcontainer
- cd ../../docker/libcontainer; git checkout tags/v1.4.0; cd - # we need exact version of libcontainer
- go get -d -v ./... && go build -v ./... # get and build source
- make
script:
- ./scripts/test.sh 2>&1 # Run test suite
notifications:
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
